apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aksdemo-e863"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aksdemo-e863"
  template:
    metadata:
      labels:
        app: "aksdemo-e863"
    spec:
      containers:
        - name: "aksdemo-e863"
          image: "acrdemo9999.azurecr.io/aksdemo"
          ports:
          - containerPort: 80