on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemo9999.azurecr.io
        username: ${{ secrets.acr_acrdemo9999_username }}
        password: ${{ secrets.acr_acrdemo9999_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemo9999.azurecr.io/aksdemo:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemo9999.azurecr.io/aksdemo:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksdemo_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aksdemo9999 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aksdemo9999`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aksdemo9999
        container-registry-url: acrdemo9999.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemo9999_username }}
        container-registry-password: ${{ secrets.acr_acrdemo9999_password }}
        secret-name: aksdemodockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aksdemo9999
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          acrdemo9999.azurecr.io/aksdemo:${{ github.sha }}
        imagepullsecrets: |
          aksdemodockerauth
